version: "3"

services:
  app:
    build:
      context: .
      args:
        NODE_ENV: development
    volumes:
      - ./:/app
      - ./backend:/app/backend
      - /app/node_modules
      - /app/backend/node_modules
    ports:
      - "3000:3000"
      - "4000:4000"
    command: npm run dev
